const DB_NAME='fieldtrack-db', STORE='companies', VERSION=1;
let db, companies=[], currentFilter='all', followWhen='due', deferredInstall=null;
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)], uid=()=>crypto.randomUUID?crypto.randomUUID():Date.now()+'-'+Math.random();
const now=()=>new Date().toISOString(); const fmt=d=>d?new Date(d).toLocaleDateString(undefined,{day:'2-digit',month:'short',year:'numeric'}):'—';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function toast(t){const x=$('#toast');x.textContent=t;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),2200)}
function openDB(){return new Promise((res,rej)=>{const r=indexedDB.open(DB_NAME,VERSION);r.onupgradeneeded=()=>r.result.createObjectStore(STORE,{keyPath:'id'});r.onsuccess=()=>{db=r.result;res()};r.onerror=()=>rej(r.error)})}
function all(){return new Promise((res,rej)=>{const r=db.transaction(STORE).objectStore(STORE).getAll();r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
function put(c){return new Promise((res,rej)=>{const r=db.transaction(STORE,'readwrite').objectStore(STORE).put(c);r.onsuccess=res;r.onerror=()=>rej(r.error)})}
function del(id){return new Promise((res,rej)=>{const r=db.transaction(STORE,'readwrite').objectStore(STORE).delete(id);r.onsuccess=res;r.onerror=()=>rej(r.error)})}
async function refresh(){companies=await all();companies.sort((a,b)=>a.name.localeCompare(b.name));renderAll()}
function nav(screen){$$('.screen').forEach(x=>x.classList.toggle('active',x.id===screen));$$('.nav').forEach(x=>x.classList.toggle('active',x.dataset.screen===screen));if(screen==='companies')renderCompanies();if(screen==='followups')renderFollowups();if(screen==='field')renderField()}
function companyCard(c,field=false){const last=(c.interactions||[]).slice(-1)[0];return `<div class="company-card" data-open="${c.id}"><div class="company-row">${field?`<button class="check ${c.visited?'done':''}" data-check="${c.id}" title="Toggle visited">${c.visited?'✓':''}</button>`:''}<div class="row-main"><div class="card-top"><span class="company-name">${esc(c.name)}</span><span class="row-arrow">›</span></div><div class="muted">${esc(c.plot||c.area||'No location added')}${c.contactPerson?' • '+esc(c.contactPerson):''}</div><div class="badges"><span class="badge ${c.visited?'visited':''}">${c.visited?'✓ VISITED':'○ PENDING'}</span>${c.priority==='High'?'<span class="badge high">HIGH</span>':''}${c.requirement?'<span class="badge req">REQUIREMENT</span>':''}${c.followUpDate?'<span class="badge follow">FOLLOW-UP</span>':''}</div>${last?`<div class="muted" style="margin-top:10px">Last: ${fmt(last.date)} • ${esc(last.type)}</div>`:''}</div></div></div>`}
function renderDashboard(){let total=companies.length,vis=companies.filter(c=>c.visited).length,cut=new Date();cut.setHours(23,59,59,999);let fu=companies.filter(c=>c.followUpDate&&new Date(c.followUpDate)<=cut).length;$('#statTotal').textContent=total;$('#statVisited').textContent=vis;$('#statPending').textContent=total-vis;$('#statFollow').textContent=fu;let focus=companies.filter(c=>!c.visited||c.followUpDate).sort((a,b)=>(a.visited-b.visited)||((a.priority==='High'?0:1)-(b.priority==='High'?0:1))).slice(0,6);$('#focusList').innerHTML=focus.length?focus.map(c=>companyCard(c)).join(''):`<div class="empty">No companies yet. Add your first company to begin.</div>`;let acts=[];companies.forEach(c=>(c.interactions||[]).forEach(i=>acts.push({...i,name:c.name})));acts.sort((a,b)=>new Date(b.date)-new Date(a.date));$('#recentList').innerHTML=acts.slice(0,6).map(i=>`<div class="activity"><b>${esc(i.name)} • ${esc(i.type)} • ${fmt(i.date)}</b><p>${esc(i.note||'No note')}</p></div>`).join('')||`<div class="empty">Your interactions will appear here.</div>`}
function matches(c,q){return !q||JSON.stringify(c).toLowerCase().includes(q.toLowerCase())}
function filterMatch(c){if(currentFilter==='all')return true;if(currentFilter==='pending')return !c.visited;if(currentFilter==='visited')return !!c.visited;if(currentFilter==='followup')return !!c.followUpDate;if(currentFilter==='requirement')return !!c.requirement;if(currentFilter==='high')return c.priority==='High';return true}
function renderCompanies(){let q=$('#searchInput').value;let arr=companies.filter(c=>filterMatch(c)&&matches(c,q));$('#companyList').innerHTML=arr.length?arr.map(c=>companyCard(c)).join(''):`<div class="empty">No matching companies.</div>`}
function renderFollowups(){let today=new Date();today.setHours(23,59,59,999),today=today.getTime();let arr=companies.filter(c=>{if(!c.followUpDate)return false;let t=new Date(c.followUpDate+'T23:59:59').getTime();return followWhen==='due'?t<=today:followWhen==='upcoming'?t>today:true}).sort((a,b)=>new Date(a.followUpDate)-new Date(b.followUpDate));$('#followupList').innerHTML=arr.length?arr.map(c=>`<div class="follow-card" data-open="${c.id}"><div class="follow-date">${fmt(c.followUpDate)}</div><div class="company-name" style="margin-top:6px">${esc(c.name)}</div><div class="muted">${esc(c.followUpNote||'Follow up')}</div>${c.requirement?`<div class="badges"><span class="badge req">${esc(c.requirement)}</span></div>`:''}</div>`).join(''):`<div class="empty">No ${followWhen==='all'?'follow-ups':followWhen+' follow-ups'}.</div>`}
function renderField(){let total=companies.length,done=companies.filter(c=>c.visited).length,p=Math.round(done/Math.max(total,1)*100);$('#fieldProgressText').textContent=`${done} / ${total} completed`,$('#fieldPercent').textContent=p+'%',$('#fieldProgress').style.width=p+'%';let f=$('#fieldFilter').value,arr=[...companies];if(f==='pending')arr.sort((a,b)=>(a.visited-b.visited));else if(f==='priority')arr.sort((a,b)=>(a.priority==='High'?0:1)-(b.priority==='High'?0:1));else if(f==='followup')arr=arr.filter(c=>c.followUpDate);$('#fieldList').innerHTML=arr.length?arr.map(c=>companyCard(c,true)).join(''):`<div class="empty">No companies in this view.</div>`}
function renderAll(){renderDashboard();renderCompanies();renderFollowups();renderField()}
function modal(html){$('#modalContent').innerHTML=html;$('#modal').classList.remove('hidden')}
function closeModal(){$('#modal').classList.add('hidden')}
function companyForm(c={}){let edit=!!c.id;modal(`<h2 class="modal-title">${edit?'Edit company':'Add company'}</h2><form id="companyForm"><div class="form-grid"><div class="field"><label>Company name *</label><input name="name" required value="${esc(c.name)}" placeholder="ABC Industries"></div><div class="field"><label>Plot / unit / address</label><input name="plot" value="${esc(c.plot)}" placeholder="Plot No. 123"></div><div class="field"><label>Area</label><input name="area" value="${esc(c.area)}" placeholder="Rabale"></div><div class="field"><label>Industry</label><input name="industry" value="${esc(c.industry)}" placeholder="Manufacturing"></div><div class="field"><label>Contact person</label><input name="contactPerson" value="${esc(c.contactPerson)}"></div><div class="field"><label>Designation / department</label><input name="designation" value="${esc(c.designation)}" placeholder="Maintenance / Purchase"></div><div class="field"><label>Phone</label><input name="phone" value="${esc(c.phone)}" inputmode="tel"></div><div class="field"><label>Email</label><input name="email" value="${esc(c.email)}" type="email"></div><div class="field"><label>Website</label><input name="website" value="${esc(c.website)}"></div><div class="field"><label>Priority</label><select name="priority"><option ${!c.priority||c.priority==='Normal'?'selected':''}>Normal</option><option ${c.priority==='High'?'selected':''}>High</option><option ${c.priority==='Low'?'selected':''}>Low</option></select></div><div class="field"><label>Requirement</label><input name="requirement" value="${esc(c.requirement)}" placeholder="e.g. HT panel / UPS / AMC"></div><div class="field"><label>Follow-up date</label><input name="followUpDate" type="date" value="${esc(c.followUpDate||'')}"></div><div class="field full"><label>Follow-up note</label><input name="followUpNote" value="${esc(c.followUpNote)}" placeholder="Call after 15 September"></div></div><div class="form-actions"><button type="button" class="secondary" id="cancelForm">Cancel</button><button class="primary">${edit?'Save changes':'Add company'}</button></div></form>`);$('#cancelForm').onclick=closeModal;$('#companyForm').onsubmit=async e=>{e.preventDefault();let n=Object.fromEntries(new FormData(e.target).entries());let duplicate=companies.find(x=>x.name.trim().toLowerCase()===n.name.trim().toLowerCase()&&x.id!==c.id);if(duplicate&&!confirm('A company with a very similar name already exists. Save anyway?'))return;let obj={...c,id:c.id||uid(),...n,visited:c.visited||false,interactions:c.interactions||[],createdAt:c.createdAt||now(),updatedAt:now()};await put(obj);await refresh();closeModal();toast(edit?'Company updated':'Company added')}}
function detail(c){let last=(c.interactions||[]).slice(-1)[0];modal(`<div><span class="eyebrow">${c.visited?'VISITED':'NOT YET VISITED'}</span><h2 class="modal-title">${esc(c.name)}</h2><div class="badges"><span class="badge ${c.visited?'visited':''}">${c.visited?'✓ VISITED':'○ PENDING'}</span>${c.priority==='High'?'<span class="badge high">HIGH PRIORITY</span>':''}</div><div class="muted" style="margin:14px 0">${esc(c.plot||'')}${c.area?' • '+esc(c.area):''}${c.industry?' • '+esc(c.industry):''}</div><div class="badges">${c.phone?`<a class="badge" href="tel:${esc(c.phone)}">📞 Call</a>`:''}${c.email?`<a class="badge" href="mailto:${esc(c.email)}">✉ Email</a>`:''}${c.phone?`<a class="badge" href="https://wa.me/${esc(c.phone.replace(/\D/g,''))}" target="_blank" rel="noopener">💬 WhatsApp</a>`:''}${c.website?`<a class="badge" href="${esc(c.website.startsWith('http')?c.website:'https://'+c.website)}" target="_blank" rel="noopener">🌐 Website</a>`:''}</div><div class="req-box"><b>LAST CONVERSATION</b>${last?`<div class="small-note">${fmt(last.date)} • ${esc(last.type)}${last.person?' • '+esc(last.person):''}</div><p style="white-space:pre-wrap;color:#b8c5d5;margin:8px 0 0">${esc(last.note||'No notes')}</p>`:'<p style="color:#8899af;margin-bottom:0">No interaction recorded yet.</p>'}</div>${c.requirement?`<div class="req-box"><b>REQUIREMENT</b><p style="margin:7px 0;color:#ffd36a">${esc(c.requirement)}</p></div>`:''}${c.followUpDate?`<div class="req-box"><b>FOLLOW-UP</b><p style="margin:7px 0;color:#d6b2ff">${fmt(c.followUpDate)} — ${esc(c.followUpNote||'')}</p></div>`:''}<div class="section-head"><h2>Interaction history</h2><button class="text-btn" id="addInteraction">＋ Add</button></div><div class="timeline">${(c.interactions||[]).slice().reverse().map(i=>`<div class="timeline-item"><div class="timeline-head"><span>${esc(i.type)}${i.person?' • '+esc(i.person):''}</span><span>${fmt(i.date)}</span></div><p>${esc(i.note||'')}</p>${i.requirement?`<div class="muted">Requirement: ${esc(i.requirement)}</div>`:''}</div>`).join('')||'<div class="empty">No interactions yet.</div>'}</div><div class="form-actions"><button class="secondary" id="editCompany">✏ Edit</button><button class="danger-btn" id="deleteCompany">Delete</button></div></div>`);$('#editCompany').onclick=()=>companyForm(c);$('#deleteCompany').onclick=async()=>{if(confirm('Delete this company and its history?')){await del(c.id);await refresh();closeModal();toast('Company deleted')}};$('#addInteraction').onclick=()=>interactionForm(c)}
function interactionForm(c){modal(`<h2 class="modal-title">Add interaction</h2><form id="interactionForm"><div class="form-grid"><div class="field"><label>Type</label><select name="type"><option>Physical Visit</option><option>Phone Call</option><option>WhatsApp</option><option>Email</option><option>Follow-up</option><option>Requirement</option></select></div><div class="field"><label>Date</label><input type="date" name="date" value="${new Date().toISOString().slice(0,10)}"></div><div class="field"><label>Person spoken to</label><input name="person" value="${esc(c.contactPerson||'')}"></div><div class="field"><label>Requirement from this interaction</label><input name="requirement" placeholder="Optional"></div><div class="field full"><label>What happened? Write freely.</label><textarea name="note" required placeholder="Conversation, response, requirement, next step, anything you want to remember..."></textarea></div></div><div class="form-actions"><button type="button" class="secondary" id="cancelInteraction">Cancel</button><button class="primary">Save interaction</button></div></form>`);$('#cancelInteraction').onclick=()=>detail(c);$('#interactionForm').onsubmit=async e=>{e.preventDefault();let i=Object.fromEntries(new FormData(e.target).entries());i.date=new Date(i.date+'T12:00:00').toISOString();c.interactions=c.interactions||[];c.interactions.push(i);c.visited=true;c.updatedAt=now();if(i.requirement)c.requirement=i.requirement;await put(c);await refresh();detail(c);toast('Interaction saved')}}
async function toggleVisit(id){let c=companies.find(x=>x.id===id);if(!c)return;c.visited=!c.visited;c.updatedAt=now();if(c.visited){c.interactions=c.interactions||[];c.interactions.push({type:'Visit status',date:now(),person:c.contactPerson||'',note:'Company marked as visited.'})}await put(c);await refresh()}
async function resetStatuses(){if(confirm('Reset every company to pending? This does not delete interaction history.')){for(const c of companies){c.visited=false;c.updatedAt=now();await put(c)}await refresh();toast('Visit status reset')}}
function download(blob,name){let a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function exportJSON(){download(new Blob([JSON.stringify({app:'FieldTrack',version:1,exportedAt:now(),companies},null,2)],{type:'application/json'}),'fieldtrack-backup.json')}
function exportCSV(){let cols=['name','plot','area','industry','contactPerson','designation','phone','email','website','priority','visited','requirement','followUpDate','followUpNote'];let rows=[cols.join(','),...companies.map(c=>cols.map(k=>`"${String(c[k]??'').replaceAll('"','""')}"`).join(','))];download(new Blob([rows.join('\n')],{type:'text/csv'}),'fieldtrack-companies.csv')}
function exportHistory(){let rows=[['Company','Date','Type','Person','Requirement','Notes']];companies.forEach(c=>(c.interactions||[]).forEach(i=>rows.push([c.name,i.date,i.type,i.person||'',i.requirement||'',i.note||''])));let csv=rows.map(r=>r.map(v=>`"${String(v).replaceAll('"','""')}"`).join(',')).join('\n');download(new Blob([csv],{type:'text/csv'}),'fieldtrack-history.csv')}
async function restore(file){try{let d=JSON.parse(await file.text());if(!Array.isArray(d.companies))throw Error();for(let c of d.companies){if(!c.id)c.id=uid();c.interactions=c.interactions||[];await put(c)}await refresh();toast('Backup restored')}catch(e){toast('Invalid backup file')}}
async function init(){await openDB();await refresh();if('serviceWorker'in navigator)navigator.serviceWorker.register('service-worker.js').catch(()=>{});}

document.addEventListener('click',e=>{let n=e.target.closest('.nav');if(n)nav(n.dataset.screen);let o=e.target.closest('[data-open]');if(o&&!e.target.closest('[data-check]')){let c=companies.find(x=>x.id===o.dataset.open);if(c)detail(c)}let chk=e.target.closest('[data-check]');if(chk){e.stopPropagation();toggleVisit(chk.dataset.check)}});
$('#addCompanyBtn').onclick=()=>companyForm();$('#addCompanyBtn2').onclick=()=>companyForm();$('#settingsBtn').onclick=()=>nav('settings');$('#closeModal').onclick=closeModal;$('#modal').onclick=e=>{if(e.target.id==='modal')closeModal()};$('#searchInput').oninput=renderCompanies;$('#filterBtn').onclick=()=>$('#filterPanel').classList.toggle('hidden');$$('#filterPanel .chip').forEach(x=>x.onclick=()=>{$$('#filterPanel .chip').forEach(y=>y.classList.remove('active'));x.classList.add('active');currentFilter=x.dataset.filter;renderCompanies()});$$('.follow-tabs .chip').forEach(x=>x.onclick=()=>{$$('.follow-tabs .chip').forEach(y=>y.classList.remove('active'));x.classList.add('active');followWhen=x.dataset.when;renderFollowups()});$('#openFieldBtn').onclick=()=>nav('field');$('#exitFieldBtn').onclick=()=>nav('dashboard');$('#fieldFilter').onchange=renderField;$('#resetSession').onclick=resetStatuses;$('#exportJson').onclick=exportJSON;$('#exportCsv').onclick=exportCSV;$('#exportHistory').onclick=exportHistory;$('#importJson').onclick=()=>$('#restoreInput').click();$('#restoreInput').onchange=e=>{if(e.target.files[0])restore(e.target.files[0])};$('#clearData').onclick=async()=>{if(confirm('Delete ALL companies and interaction history? This cannot be undone.')){await new Promise((res,rej)=>{let tx=db.transaction(STORE,'readwrite');let r=tx.objectStore(STORE).clear();tx.oncomplete=res;tx.onerror=()=>rej(tx.error)});await refresh();toast('All data cleared')}};
window.addEventListener('beforeinstallprompt',e=>{deferredInstall=e;$('#installBtn').hidden=false});$('#installBtn').onclick=async()=>{if(!deferredInstall)return;try{const choice=await deferredInstall.prompt();if(choice?.outcome==='accepted')toast('App installation started');else toast('Installation not completed')}catch(err){console.warn('Install prompt could not be shown:',err)}finally{deferredInstall=null;$('#installBtn').hidden=true}};window.addEventListener('appinstalled',()=>{deferredInstall=null;$('#installBtn').hidden=true;toast('FieldTrack installed')});init().catch(e=>{console.error(e);toast('App could not initialize')});
